from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 640)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.MarkdownText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_7.addWidget(self.label)
        self.aprendizaje = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.aprendizaje.sizePolicy().hasHeightForWidth())
        self.aprendizaje.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.aprendizaje.setFont(font)
        self.aprendizaje.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.aprendizaje.setAlignment(QtCore.Qt.AlignCenter)
        self.aprendizaje.setObjectName("aprendizaje")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.aprendizaje)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(self.aprendizaje)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setWidgetResizable(False)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 353, 282))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_3.addWidget(self.scrollArea, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem, 1, 0, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnPatrones = QtWidgets.QPushButton(self.aprendizaje)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btnPatrones.setFont(font)
        self.btnPatrones.setLocale(QtCore.QLocale(QtCore.QLocale.Spanish, QtCore.QLocale.Argentina))
        self.btnPatrones.setObjectName("btnPatrones")
        self.horizontalLayout.addWidget(self.btnPatrones)
        self.btnAprender = QtWidgets.QPushButton(self.aprendizaje)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.btnAprender.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btnAprender.setFont(font)
        self.btnAprender.setStyleSheet("")
        self.btnAprender.setLocale(QtCore.QLocale(QtCore.QLocale.Spanish, QtCore.QLocale.Argentina))
        self.btnAprender.setObjectName("btnAprender")
        self.horizontalLayout.addWidget(self.btnAprender)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.btnMatriz = QtWidgets.QPushButton(self.aprendizaje)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btnMatriz.setFont(font)
        self.btnMatriz.setLocale(QtCore.QLocale(QtCore.QLocale.Spanish, QtCore.QLocale.Argentina))
        self.btnMatriz.setObjectName("btnMatriz")
        self.verticalLayout_5.addWidget(self.btnMatriz)
        self.gridLayout_3.addLayout(self.verticalLayout_5, 2, 0, 1, 1)
        self.horizontalLayout_5.addLayout(self.gridLayout_3)
        self.verticalLayout_7.addWidget(self.aprendizaje)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.entrenamiento = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.entrenamiento.setFont(font)
        self.entrenamiento.setAlignment(QtCore.Qt.AlignCenter)
        self.entrenamiento.setObjectName("entrenamiento")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.entrenamiento)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.btnPatronIncompleto = QtWidgets.QPushButton(self.entrenamiento)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btnPatronIncompleto.setFont(font)
        self.btnPatronIncompleto.setLocale(QtCore.QLocale(QtCore.QLocale.Spanish, QtCore.QLocale.Argentina))
        self.btnPatronIncompleto.setObjectName("btnPatronIncompleto")
        self.verticalLayout_4.addWidget(self.btnPatronIncompleto)
        self.btnResultado = QtWidgets.QPushButton(self.entrenamiento)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btnResultado.setFont(font)
        self.btnResultado.setLocale(QtCore.QLocale(QtCore.QLocale.Spanish, QtCore.QLocale.Argentina))
        self.btnResultado.setObjectName("btnResultado")
        self.verticalLayout_4.addWidget(self.btnResultado)
        self.horizontalLayout_3.addWidget(self.entrenamiento)
        self.verticalLayout_7.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6.addLayout(self.verticalLayout_7)
        spacerItem1 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.patrones = QtWidgets.QVBoxLayout()
        self.patrones.setObjectName("patrones")
        self.patronIncompleto = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.patronIncompleto.sizePolicy().hasHeightForWidth())
        self.patronIncompleto.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.patronIncompleto.setFont(font)
        self.patronIncompleto.setAlignment(QtCore.Qt.AlignCenter)
        self.patronIncompleto.setObjectName("patronIncompleto")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.patronIncompleto)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mplPatronIncompleto = MplWidget(self.patronIncompleto)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mplPatronIncompleto.sizePolicy().hasHeightForWidth())
        self.mplPatronIncompleto.setSizePolicy(sizePolicy)
        self.mplPatronIncompleto.setObjectName("mplPatronIncompleto")
        self.verticalLayout.addWidget(self.mplPatronIncompleto)
        self.patrones.addWidget(self.patronIncompleto)
        self.patronResultante = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.patronResultante.setFont(font)
        self.patronResultante.setAlignment(QtCore.Qt.AlignCenter)
        self.patronResultante.setObjectName("patronResultante")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.patronResultante)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.mplResultado = MplWidget(self.patronResultante)
        self.mplResultado.setObjectName("mplResultado")
        self.verticalLayout_2.addWidget(self.mplResultado)
        self.patrones.addWidget(self.patronResultante)
        self.horizontalLayout_6.addLayout(self.patrones)
        self.gridLayout_2.addLayout(self.horizontalLayout_6, 0, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Redes de Hopfield"))
        self.label.setText(_translate("MainWindow", "REDES DE HOPFIELD"))
        self.btnPatrones.setText(_translate("MainWindow", "Patrones"))
        self.btnAprender.setText(_translate("MainWindow", "Aprender"))
        self.btnMatriz.setText(_translate("MainWindow", "Mostrar matriz"))
        self.entrenamiento.setTitle(_translate("MainWindow", "🔍 Reconocer"))
        self.btnPatronIncompleto.setText(_translate("MainWindow", "Patrón Incompleto"))
        self.btnResultado.setText(_translate("MainWindow", "Resultado"))
        self.patronIncompleto.setTitle(_translate("MainWindow", "Patrón incompleto"))
        self.patronResultante.setTitle(_translate("MainWindow", "Patrón reconocido"))
from src.gui.utils.mplwidget import MplWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
